version: "2"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
   